#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
