#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me and customizes 404 not found
sudo apt-get -y update
sudo apt-get -y install nginx

sudo sh -c "echo '
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        error_page 404 /404.html;
        location = /404.html {
                internal;
                echo \"Ceci n'est pas une page\";
        }
        # ...
}' > /etc/nginx/sites-available/default"

sudo service nginx restart
