#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 132505-web-01 100.26.219.194:80 check
    server 132505-web-02 52.204.61.174:80 check
"

apt-get -y update
apt-get -y upgrade


apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update


apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
